### ISSUE TITLE
When in multimonitor, offsets for the non-primary monitors are incorrect

### ISSUE THREAD

**Issue by alex-laties** [alex-laties/tumblrtv-screensaver-osx#2]
They end up way off screen, resulting in the screensaver not showing on non-primary monitors in offset layouts.

**Comment by byxorna** [comment]
This happens to me when display layout changes (i.e undocking from external monitors)

**Comment by alex-laties** [comment]
Fixed with https://github.com/alex-laties/tumblrtv-screensaver-osx/commit/52979b50643d13d7ff47e66620a9d5136262eedb

Will roll a new release

**Comment by alex-laties** [comment]
https://github.com/alex-laties/tumblrtv-screensaver-osx/releases/tag/v0.1.2
